### ISSUE TITLE
Enum namiesto this.getClass().getSimpleName()

### ISSUE THREAD

**Issue by Klingacik** [gachojuraj/BackendExercises#1]
Skús namiesto this.getClass().getSimpleName() použiť Enum. V tomto prípade to vychádza, že požadovaný výpis je zhodný s názvami tried ale čo keby to tak nebolo? Navyše je prehľadnejšie a čitateľnejšie mať zoznam všetkých možných typov zamestnaní (alebo aj čohokoľvek iného) uložené v Enum-e.

https://github.com/gachojuraj/BackendExercises/blob/9feb252945bf0eca35814f3b68ffe0d1ec661274/src/sk/jurij/BackendExercises/model/Employee.java#L12

**Comment by gachojuraj** [comment]
fixed
https://github.com/gachojuraj/BackendExercises/blob/master/src/sk/jurij/BackendExercises/model/EmployeeType.java
