### ISSUE TITLE
Set

### ISSUE THREAD

**Issue by Klingacik** [gachojuraj/BackendExercises#3]
Pekne si popísal aj odpovede na doplňujúce otázky. Pokiaľ ale viem tak Set elementy neusporiada sám od seba. Odkiaľ vieš, že ich usporiada?

https://github.com/gachojuraj/BackendExercises/blob/9feb252945bf0eca35814f3b68ffe0d1ec661274/src/sk/jurij/BackendExercises/CollectionsExercises.java#L64

**Comment by gachojuraj** [comment]
fixed
https://github.com/gachojuraj/BackendExercises/blob/c3f623dfc583b9b4f2239a1cda17032ac55f87d8/src/sk/jurij/BackendExercises/CollectionsExercises.java#L62
