### ISSUE TITLE
Interface vs Concrete implementation

### ISSUE THREAD

**Issue by Klingacik** [gachojuraj/BackendExercises#4]
Skús si na nete pohľadať prečo je lepšie používať ako typ parametra v metóde alebo tiež typ atribútu List a nie ArrayList. Aj u nás v práci používame interface List a nie priamo ArrayList ako typ. Až keď inicializujem napíšem napr. List<String> list = new ArrayList<>(). Podobne je to pre Map, Set a tiež pre interface, ktorý vytvoríš ty ako napr. EmployeeService. Skús to poupravovať.

https://github.com/gachojuraj/BackendExercises/blob/9feb252945bf0eca35814f3b68ffe0d1ec661274/src/sk/jurij/BackendExercises/CollectionsExercises.java#L18

**Comment by gachojuraj** [comment]
fixed
https://github.com/gachojuraj/BackendExercises/blob/c3f623dfc583b9b4f2239a1cda17032ac55f87d8/src/sk/jurij/BackendExercises/CollectionsExercises.java#L16
